language: java
jdk: oraclejdk8
sudo: false

before_install: chmod +x gradlew
install:
  - ""
script:
  - ./gradlew --continue check javadoc
  - find ~/.gradle/ -name *.lock -print0 | xargs -0 rm -f

cache:
  directories:
  - ~/.gradle

notifications:
  email: false
